import type { Metadata } from "next";
import { NavBar } from "@/public/components/NavBar";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col  py-[2%]  items-center main-background`}
      >
        <div className="max-w-[80%] bg-white">
          <NavBar />
          {children}
          </div>
      </body>
    </html>
  );
}
