import type { Metadata } from "next";
import { NavBar } from "@/public/components/NavBar";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen px-[10%] py-[2%] justify-start items-center main-background`}
      >
          <NavBar />
          {children}
      </body>
    </html>
  );
}
